plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'org.sportsnow.tv.utilities'
    compileSdk 34

    defaultConfig {
        minSdk 30
        targetSdk 34
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }
}

dependencies {
    api 'org.jetbrains.kotlin:kotlin-stdlib'
    api project(':list')
}
